
import {
  ArrowRight,
  BookOpen,
  Check,
  ChevronsUpDown,
  Circle,
  Copy,
  Edit,
  ExternalLink,
  File,
  HelpCircle,
  Home,
  LayoutGrid,
  Loader2,
  Mail,
  MapPin,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Trash,
  User,
  X,
  Workflow,
  Heart,
  Briefcase,
  Menu,
  Star,
  BedDouble,
  CalendarDays,
  Users,
  AlertTriangle, // For error states
  RefreshCw,     // For "Try Again" buttons
  CalendarX,     // For "No Bookings" or "No Favorites"
  Image, // For placeholder image icon
  LayoutDashboard, // For Admin Dashboard
  Hotel, // For Admin Accommodations
  Building2, // Alternative for Accommodations
  Trash2, // For delete actions
} from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  bookOpen:BookOpen,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  layoutGrid: LayoutGrid,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  mapPin: MapPin,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  trash2: Trash2,
  user: User,
  heart: Heart,
  briefcase: Briefcase,
  menu: Menu,
  star: Star,
  bedDouble: BedDouble,
  calendarDays: CalendarDays,
  users: Users,
  alertTriangle: AlertTriangle,
  refreshCw: RefreshCw,
  calendarX: CalendarX,
  image: Image,
  layoutDashboard: LayoutDashboard,
  hotel: Hotel,
  building2: Building2,
};

export {Icons};
